
name: practical

on:
  push:
    branches:
      - main


jobs:
  
  build_job:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: ls -al dist
      - name: Zip the buid/dist file
        run: zip dist.zip ./dist -r
      - name: Upload Build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist.zip
          retention-days: 1

  deploy_job:
    name: deploy
    needs: build_job
    runs-on: ubuntu-20.04
    steps:
    - name: install ssh keys in image vm (- runs-on)
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP }} > ~/.ssh/known_hosts
    - name: Download Build artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: build
    - name: list files in build file
      run: ls -al
    - name: Unzip the downloaded build file
      run: unzip dist.zip
    - name: list files in build file
      run: ls -al
    - name: move build file to server
      run: scp -r dist/* ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/practical/dist/
    - name: run setup file in server
      run: ssh ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "cd ~/lakshmithati/ && ./practical.setup.sh && exit"
    - name: cleanup ssh keys in image vm (- runs-on)
      run: rm -rf ~/.ssh
